---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-net
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: weave
          env:
            - name: IPTABLES_BACKEND
              value: "legacy"
        - name: weave-npc
          env:
            - name: IPTABLES_BACKEND
              value: "legacy"
      initContainers:
        - name: weave-init
          env:
            - name: IPTABLES_BACKEND
              value: "legacy"
