apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: kurl-builtin
spec:
  hostCollectors:
    - hostOS: {}
  analyzers:
    - hostOS:
        outcomes:
          - fail:
              when: "centos = 7"
              message: "containerd-1.2.13 is not supported on CentOS 7"
          - fail:
              when: "ol = 7"
              message: "containerd-1.2.13 is not supported on Oracle Linux 7"
          - fail:
              when: "ubuntu = 22.04"
              message: "containerd-1.2.13 is not supported on Ubuntu 22.04"
