apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: testgrid-postgres
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        value: postgres://testgrid:password@https://testgrid-postgres-$OKTETO_NAMESPACE.replicated.okteto.dev/testgrid?sslmode=disable
