apiVersion: v1
kind: Service
metadata:
  name: testgrid-web
  labels:
    app: testgrid-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 30880
    targetPort: http
  selector:
    app: testgrid-web
