- name: "prometheus minimal"
  installerSpec:
    kubernetes:
      version: "latest"
    weave:
      version: "latest"
    rook:
      version: "1.6.x"
      isBlockStorageEnabled: true
    docker:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "promethus upgrade from 0.33.0"
  installerSpec:
    kubernetes:
      version: "latest"
    weave:
      version: "latest"
    rook:
      version: "1.6.x"
      isBlockStorageEnabled: true
    docker:
      version: "latest"
    prometheus:
      version: "0.33.0"
  upgradeSpec:
    kubernetes:
      version: "latest"
    weave:
      version: "latest"
    rook:
      version: "1.6.x"
      isBlockStorageEnabled: true
    docker:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus upgrade from latest"
  installerSpec:
    kubernetes:
      version: "latest"
    weave:
      version: "latest"
    rook:
      version: "1.6.x"
      isBlockStorageEnabled: true
    docker:
      version: "latest"
    prometheus:
      version: "latest"
  upgradeSpec:
    kubernetes:
      version: "latest"
    weave:
      version: "latest"
    rook:
      version: "1.6.x"
      isBlockStorageEnabled: true
    docker:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus with longhorn and containerd"
  installerSpec:
    kubernetes:
      version: "1.21.x"
    weave:
      version: "latest"
    longhorn:
      version: "latest"
    containerd:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
- name: "prometheus minimal airgap"
  installerSpec:
    kubernetes:
      version: "latest"
    weave:
      version: "latest"
    rook:
      version: "1.6.x"
      isBlockStorageEnabled: true
    docker:
      version: "latest"
    prometheus:
      version: "__testver__"
      s3Override: "__testdist__"
  airgap: true
