---
apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen-v1.21.0
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
      - name: contour
        imagePullPolicy: IfNotPresent
