name: test-testgrid-results

on:
  schedule:
    - cron: "0/15 * * * *"
  push:
    branches:
      - seanrester/sc-47380/move-kots-kurl-add-on-from-kurl-to-kots-project

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-addons:
    if: ${{ github.repository_owner == 'replicatedhq' && github.actor != 'dependabot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/testgrid-checker
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
